### ISSUE TITLE
Please release the ASM->CPP translation tool

### ISSUE THREAD

**Issue by LinoMastro** [zaps166/NFSIISE-CPP#3]
Hi, could you please release as open source the tool that you use to auto-generate the CPP translation?

I understand that there are likely bits that are specific for NSF and not a general translation for all of x86-32, but even in its current state I think it would an invaluable resource for similar projects.

Having access to the CPU, FPU and Application classes under an open source license would be incredibly useful.

Thanks!

**Comment by zaps166** [comment]
Released: https://github.com/zaps166/NfsAsmToC

I kept disabled code and my original comments (in Polish language).

Software is reading `NFS2SE.asm` from working directory (available [here](https://github.com/zaps166/NFSIISE-ASM/blob/master/NFS2SE.asm)) and produces `NFS2SE.cpp` in working directory.

Requirements: Qt5, C++14, qmake.
Requirements for tests (incomplete, but enough to me to test it): 32-bit only, C++14, Qt5, qbs.

GCC compiler is needed to compile generated CPP code, because `-fpermissive` option is needed.
